"""Add douyin tables for miniapp integration

Revision ID: a9b8c7d6e5f4
Revises: 1a31ce608336
Create Date: 2024-12-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9b8c7d6e5f4'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建抖音用户表
    op.create_table('douyin_users',
        sa.Column('openid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('unionid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('user_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('permission', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('last_login_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_douyin_users_openid'), 'douyin_users', ['openid'], unique=False)
    op.create_index(op.f('ix_douyin_users_unionid'), 'douyin_users', ['unionid'], unique=False)
    
    # 创建标点信息表
    op.create_table('biaodian_items',
        sa.Column('latitude', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('longitude', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('beizhu', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('weather', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('zhuangbei', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('fishing_type', sa.Integer(), nullable=False),
        sa.Column('yuhuo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('tuijian', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('openid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['douyin_users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biaodian_items_openid'), 'biaodian_items', ['openid'], unique=False)
    
    # 创建登录日志表
    op.create_table('douyin_login_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('openid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
        sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('login_result', sa.Integer(), nullable=False),
        sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_douyin_login_logs_openid'), 'douyin_login_logs', ['openid'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除登录日志表
    op.drop_index(op.f('ix_douyin_login_logs_openid'), table_name='douyin_login_logs')
    op.drop_table('douyin_login_logs')
    
    # 删除标点信息表
    op.drop_index(op.f('ix_biaodian_items_openid'), table_name='biaodian_items')
    op.drop_table('biaodian_items')
    
    # 删除抖音用户表
    op.drop_index(op.f('ix_douyin_users_unionid'), table_name='douyin_users')
    op.drop_index(op.f('ix_douyin_users_openid'), table_name='douyin_users')
    op.drop_table('douyin_users')
    
    # ### end Alembic commands ###