# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x07service\")\n\rEncryptedData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\n\n\x02iv\x18\x02 \x01(\t\"O\n\x0fShowDataRequest\x12-\n\rencryptedData\x18\x01 \x01(\x0b\x32\x16.service.EncryptedData\x12\r\n\x05token\x18\x02 \x01(\t\"Y\n\x10ShowDataResponse\x12\x0f\n\x07\x65rrCode\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\x15\n\rdecryptedData\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"\x1c\n\x0cLoginRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"`\n\rLoginResponse\x12\x0f\n\x07\x65rrCode\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0e\n\x06openid\x18\x04 \x01(\t\x12\x0f\n\x07unionid\x18\x05 \x01(\t\"\x18\n\x08UserData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\x0fUserDataRequest\x12\r\n\x05token\x18\x01 \x01(\t\"X\n\x10UserDataResponse\x12\x0f\n\x07\x65rrCode\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12#\n\x08userData\x18\x03 \x01(\x0b\x32\x11.service.UserData\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"1\n\x0eLogoutResponse\x12\x0f\n\x07\x65rrCode\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\tB.\n\rtoutiao.modelZ\x07./model\xca\x02\x05Model\xe2\x02\x0bGPBMetaDatab\x06proto3')



_ENCRYPTEDDATA = DESCRIPTOR.message_types_by_name['EncryptedData']
_SHOWDATAREQUEST = DESCRIPTOR.message_types_by_name['ShowDataRequest']
_SHOWDATARESPONSE = DESCRIPTOR.message_types_by_name['ShowDataResponse']
_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
_USERDATA = DESCRIPTOR.message_types_by_name['UserData']
_USERDATAREQUEST = DESCRIPTOR.message_types_by_name['UserDataRequest']
_USERDATARESPONSE = DESCRIPTOR.message_types_by_name['UserDataResponse']
_LOGOUTREQUEST = DESCRIPTOR.message_types_by_name['LogoutRequest']
_LOGOUTRESPONSE = DESCRIPTOR.message_types_by_name['LogoutResponse']
EncryptedData = _reflection.GeneratedProtocolMessageType('EncryptedData', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTEDDATA,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.EncryptedData)
  })
_sym_db.RegisterMessage(EncryptedData)

ShowDataRequest = _reflection.GeneratedProtocolMessageType('ShowDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOWDATAREQUEST,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.ShowDataRequest)
  })
_sym_db.RegisterMessage(ShowDataRequest)

ShowDataResponse = _reflection.GeneratedProtocolMessageType('ShowDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOWDATARESPONSE,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.ShowDataResponse)
  })
_sym_db.RegisterMessage(ShowDataResponse)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

UserData = _reflection.GeneratedProtocolMessageType('UserData', (_message.Message,), {
  'DESCRIPTOR' : _USERDATA,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.UserData)
  })
_sym_db.RegisterMessage(UserData)

UserDataRequest = _reflection.GeneratedProtocolMessageType('UserDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERDATAREQUEST,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.UserDataRequest)
  })
_sym_db.RegisterMessage(UserDataRequest)

UserDataResponse = _reflection.GeneratedProtocolMessageType('UserDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERDATARESPONSE,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.UserDataResponse)
  })
_sym_db.RegisterMessage(UserDataResponse)

LogoutRequest = _reflection.GeneratedProtocolMessageType('LogoutRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUTREQUEST,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.LogoutRequest)
  })
_sym_db.RegisterMessage(LogoutRequest)

LogoutResponse = _reflection.GeneratedProtocolMessageType('LogoutResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUTRESPONSE,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:service.LogoutResponse)
  })
_sym_db.RegisterMessage(LogoutResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rtoutiao.modelZ\007./model\312\002\005Model\342\002\013GPBMetaData'
  _ENCRYPTEDDATA._serialized_start=24
  _ENCRYPTEDDATA._serialized_end=65
  _SHOWDATAREQUEST._serialized_start=67
  _SHOWDATAREQUEST._serialized_end=146
  _SHOWDATARESPONSE._serialized_start=148
  _SHOWDATARESPONSE._serialized_end=237
  _LOGINREQUEST._serialized_start=239
  _LOGINREQUEST._serialized_end=267
  _LOGINRESPONSE._serialized_start=269
  _LOGINRESPONSE._serialized_end=365
  _USERDATA._serialized_start=367
  _USERDATA._serialized_end=391
  _USERDATAREQUEST._serialized_start=393
  _USERDATAREQUEST._serialized_end=425
  _USERDATARESPONSE._serialized_start=427
  _USERDATARESPONSE._serialized_end=515
  _LOGOUTREQUEST._serialized_start=517
  _LOGOUTREQUEST._serialized_end=547
  _LOGOUTRESPONSE._serialized_start=549
  _LOGOUTRESPONSE._serialized_end=598
# @@protoc_insertion_point(module_scope)
